---
clone:
  depth: 1
kind: pipeline
name: AzurePipeline
steps:
  -
    commands:
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/KazuDante89/lavender_lineage_kernel/A12.1-Newbie-Pelt/build.sh | bash"
    environment:
      TOKEN:
        from_secret: token
    image: panchajanya1999/archlinux:latest
    name: Azure-Images
    trigger:
      branch:
        - A12.1-Newbie-Pelt
